Add additional log for pipelining sightings.
center-for-threat-informed-defense/sightings_ecosystem pull request #9
Opened 2022-07-19 19:29 UTC by zmallen

When someone wants to experiment with sightings with less than 1000
sightings, they are unable to do so due to the constraint of
`db_batch_ingest_size` being 1000. Change this to an environment
variable, as well as logic around per file commit processing rather than
waiting for the 1000 number.

2022-07-19 19:29 UTC, zmallen commented
relates to #8

2022-07-19 19:30 UTC, zmallen commented on src/pipeline/pipeline.py
> +db_ingest_batch_size = os.getenv("db_ingest_batch_size", 1000)
this is a ~cleaner way to process environment variables than accessing the os environment dictionary. Provides a default value out of the gate :)

2022-08-15 18:10 UTC, nschwane requested changes

2022-08-15 18:10 UTC, nschwane commented on src/pipeline/pipeline.py
> +def db_batched_commit_sightings(session, last_sightings_from_file):  # pragma: no covers
Giving this new keyword argument a default value (`last_sightings_from_file=False`) makes this code backwards compatible if others were using this module as a library versus just running it as a script.

2024-03-12 13:01 UTC, closed without merging